name: tech-assesment-dm
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-assesment-dm
    restart: unless-stopped
    command: npm run dev
    ports:
      - mode: ingress
        target: 3000
        published: 8080
        protocol: tcp
    volumes:
      - ./src:/app/src
    networks:
      - app-network
    depends_on:
      - db
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-assesment-dm
    command: npm run test # test:watch to keep it running on changes
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    networks:
      - app-network
    depends_on:
      - db
  db:
    environment:
      POSTGRES_DB: dm
      POSTGRES_PASSWORD: dm
      POSTGRES_USER: dm
    image: postgres:15
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - mode: ingress
        target: 5432
        published: 7654
        protocol: tcp
    networks:
      - app-network
volumes:
  data: {}
networks:
  app-network:
    driver: bridge
